declare interface ActionKitEvent {
    address1: string,
    address2: string,
    attendee_count: number,
    // campaign: Campaign | URI
    city: string,
    confirmed_at: Date,
    country: string,
    created_at: Date,
    // creator: Person | URI
    directions: string,
    ends_at: Date,
    ends_at_utc: Date,
    // fields: [CustomField]
    host_is_confirmed: boolean,
    id: number,
    is_approved: boolean,
    is_private: boolean,
    latitude: number,
    longitude: number,
    max_attendees: number,
    note_to_attendees: number,
    notes: string,
    phone: string,
    plus4: string,
    postal: string,
    public_description: string,
    region: string,
    resource_uri: string,
    // signups: [Signup|URI]
    starts_at: Date,
    starts_at_utc: Date,
    state: string,
    status: string,
    title: string,
    updated_at: Date,
    venue: string,
    zip: string,
}
