declare interface ActionKitPerson {
    address1: string,
    address2: string,
    city: string,
    country: string,
    created_at: Date,
    email: string,
    fields?: [object],
    first_name: string,
    id: number,
    lang?: string, // uri
    last_name: string,
    middle_name: string,
    phones: [ActionKitPhone|string],
    plus4: string,
    postal: string,
    prefix: string,
    rand_id: number,
    region: string,
    resource_uri: string,
    source: string,
    state: string,
    subscription_status: string,
    suffix: string,
    updated_at: Date,
    zip: string
}
