declare interface VanPerson {
    vanId: number,
    firstName: string,
    middleName: string,
    lastName: string,
    dateOfBirth: Date,
    party: string,
    sex: "M" | "F",
    salutation: string,
    envelopeName: string,
    title: string,
    suffix: string,
    nickname: string,
    website: string,
    contactMethodPreferenceCode: "P" | "E" | "M" | "S",
    employer: string,
    occupation: string,
    // emails: [VanEmail],
    // phones: [VanPhone],
    // addresses: [VanAddress],
    // recordedAddresses: [VanAddress],
    // identifiers: [VanIdentifier],
    // customFieldValues: [VanCustomField],
    selfReportedRaces?: [object]
    selfReportedEthnicities?: [object],
    selfReportedLanguagePreference?: object,
    selfReportedSexualOrientations?: [object],
    selfReportedGenders?: [object],
    suppressions?: [object],
    disclosureFieldValues?: [object]
}
